name: ci/gh-actions/depends

on:
  push:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "**/README.md"

env:
  APT_SET_CONF: |
    tee -a /etc/apt/apt.conf.d/80-custom << EOF
    Acquire::Retries "3";
    Acquire::http::Timeout "120";
    Acquire::ftp::Timeout "120";
    EOF

  CCACHE_SETTINGS: |
    ccache --max-size=150M
    ccache --set-config=compression=true

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - name: "RISCV 64bit"
            host: "riscv64-linux-gnu"
            packages: "g++-riscv64-linux-gnu"

          - name: "ARM v8"
            host: "aarch64-linux-gnu"
            packages: "g++-aarch64-linux-gnu"

          - name: "x86_64 Linux"
            host: "x86_64-unknown-linux-gnu"

          - name: "Win64"
            host: "x86_64-w64-mingw32"
            packages: "g++-mingw-w64-x86-64"

    name: ${{ matrix.toolchain.name }}

    steps:
      - name: install dependencies
        run: |
          set -euxo pipefail
          ${{env.APT_SET_CONF}}

          sudo apt update
          sudo apt -y install \
            build-essential libtool cmake autotools-dev automake pkg-config \
            python3 gperf bsdmainutils curl git ca-certificates unzip ccache \
            ${{ matrix.toolchain.packages }}

      - name: install Go
        run: |
          set -euxo pipefail
          curl -LO https://go.dev/dl/go1.23.8.linux-amd64.tar.gz
          sudo tar -C /usr/local -xzf go1.23.8.linux-amd64.tar.gz
          echo "/usr/local/go/bin" >> $GITHUB_PATH
          go version

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: ccache
        uses: actions/cache@v4
        with:
          path: ~/.ccache
          key: ccache-${{ matrix.toolchain.host }}-${{ github.sha }}
          restore-keys: ccache-${{ matrix.toolchain.host }}-

      - name: depends cache
        uses: actions/cache@v4
        with:
          path: contrib/depends/built
          key: depends-${{ matrix.toolchain.host }}-${{ hashFiles('contrib/depends/packages/*') }}
          restore-keys: depends-${{ matrix.toolchain.host }}-

      - name: build depends
        run: |
          set -euxo pipefail
          ${{env.CCACHE_SETTINGS}}

          rm -rf contrib/depends/built

          make depends \
            target=${{ matrix.toolchain.host }} \
            -j$(nproc)

  build-macos:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - name: "Cross-Mac x86_64"
            host: "x86_64-apple-darwin"

          - name: "Cross-Mac arm64"
            host: "arm64-apple-darwin"

    name: ${{ matrix.toolchain.name }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: install dependencies
        run: |
          set -euxo pipefail
          brew update
          brew install ccache cmake boost openssl zeromq libsodium

      - name: ccache
        run: |
          ccache --max-size=150M
          ccache --set-config=compression=true

      - name: build depends
        run: |
          set -euxo pipefail

          rm -rf contrib/depends/built

          make depends \
            target=${{ matrix.toolchain.host }} \
            -j$(sysctl -n hw.ncpu)
